version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    user: "node"
    volumes:
      - ./frontend:/myapp/frontend
      - ./frontend/node_modules:/myapp/frontend/node_modules
      - ./frontend/yarn-cache:/usr/local/share/.cache/yarn
    ports:
      - "3000:3000"
    command: "yarn run dev"
    depends_on:
      - backend
