version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - psql_data:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp/backend
      - bundle_path:/backend/bundle
    environment:
      - BUNDLE_PATH=/backend/bundle
    env_file:
      - '.env'
    ports:
      - "8000:8000"
    depends_on:
      - db
  # frontend:
  #   build: ./frontend
  #   user: "node"
  #   volumes:
  #     - ./frontend:/myapp/frontend
  #     - node_modules:/myapp/frontend/node_modules
  #     - ./frontend/yarn-cache:/usr/local/share/.cache/yarn
  #   ports:
  #     - "4000:4000"
  #   command: "yarn run dev"
  #   depends_on:
  #     - backend

volumes:
  psql_data:
  bundle_path:
  # node_modules:
